name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Instalar y construir el frontend
    - name: Install and build frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm run build --if-present

    # Instalar y construir el backend
    - name: Install and build backend
      working-directory: ./backend
      run: |
        npm ci
        npm run build --if-present

    # Ejecutar pruebas (si las tienes) para el frontend
    - name: Test frontend
      working-directory: ./frontend
      run: npm test --if-present

    # Ejecutar pruebas (si las tienes) para el backend
    - name: Test backend
      working-directory: ./backend
      run: npm test --if-present

