name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    # Setup Node.js y Cache para Frontend
    - name: Setup Node.js ${{ matrix.node-version }} for frontend
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    # Instalar dependencias del frontend
    - name: Install dependencies for frontend
      working-directory: ./frontend
      run: npm ci

    # Construir y probar el frontend
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build --if-present
    - name: Test frontend
      working-directory: ./frontend
      run: npm test --if-present

    # Setup Node.js y Cache para Backend
    - name: Setup Node.js ${{ matrix.node-version }} for backend
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    # Instalar dependencias del backend
    - name: Install dependencies for backend
      working-directory: ./backend
      run: npm ci

    # Construir y probar el backend
    - name: Build backend
      working-directory: ./backend
      run: npm run build --if-present
    - name: Test backend
      working-directory: ./backend
      run: npm test --if-present

